version: 2
jobs:
  format_plan:
    docker:
      -  image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          command: terraform fmt
      - run:
          command: terraform validate
      - run:
          command: terraform plan

  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          command: terraform apply -auto-approve

workflows:
  version: 2
  build_test:
    jobs:
      - apply:
          filters:
            branches:
              only: master
          requires:
            - format_plan
      - format_plan:
          filters:
            branches:
              only: master

